import type { Category, CategoryQuizData } from './types';

export const categories: Category[] = [
  {
    id: 'technology',
    name: 'Technology',
    description: 'Computers, devices, software and the technologies shaping the modern world.',
    icon: '💻',
  },
  {
    id: 'history',
    name: 'History',
    description: 'Important people, events, civilizations and turning points.',
    icon: '🏛️',
  },
  {
    id: 'medicine',
    name: 'Medicine',
    description: 'Basic medical knowledge, human biology and healthcare concepts.',
    icon: '🩺',
  },
  {
    id: 'artificial-intelligence',
    name: 'Artificial Intelligence',
    description: 'AI concepts, applications and how intelligent systems work.',
    icon: '🤖',
  },
  {
    id: 'machine-learning',
    name: 'Machine Learning',
    description: 'Core ML concepts, models, training and practical applications.',
    icon: '🧠',
  },
  {
    id: 'programming-languages',
    name: 'Programming Languages',
    description: 'Programming concepts and practical knowledge across popular languages.',
    icon: '💾',
  },
  {
    id: 'art',
    name: 'Art',
    description: 'Art movements, artists, techniques and visual culture.',
    icon: '🎨',
  },
];

export const categoryQuizData: Record<string, CategoryQuizData> = {
  technology: {
    category: categories[0],
    questions: [
      {
        id: "1",
        text: 'What does "HTTP" stand for?',
        options: [
          'HyperText Transfer Protocol',
          'High Transfer Text Protocol',
          'Hyperlink Text Transfer Process',
          'Home Tool Transfer Protocol',
        ],
        correctAnswer: 0,
        explanation: 'HTTP (HyperText Transfer Protocol) is the foundation of data communication on the World Wide Web.',
      },
      {
        id: "2",
        text: 'Which company developed the Windows operating system?',
        options: ['Apple', 'Microsoft', 'Google', 'IBM'],
        correctAnswer: 1,
        explanation: 'Microsoft developed Windows, first released in 1985 as a graphical operating system shell for MS-DOS.',
      },
      {
        id: "3",
        text: 'What is the main function of a router in a network?',
        options: [
          'To connect devices to the internet directly',
          'To forward data packets between computer networks',
          'To store files for network users',
          'To encrypt all network traffic',
        ],
        correctAnswer: 1,
        explanation: 'A router connects multiple networks and forwards data packets between them, directing traffic efficiently.',
      },
      {
        id: "4",
        text: 'What does "URL" stand for?',
        options: [
          'Universal Resource Locator',
          'Uniform Resource Locator',
          'Universal Reference Link',
          'Uniform Reference Locator',
        ],
        correctAnswer: 1,
        explanation: 'URL (Uniform Resource Locator) is the address used to access resources on the internet.',
      },
      {
        id: "5",
        text: 'Which technology is used for wireless communication over short distances?',
        options: ['Bluetooth', 'Ethernet', 'Fiber optic', 'Coaxial cable'],
        correctAnswer: 0,
        explanation: 'Bluetooth is a wireless technology standard for exchanging data over short distances using radio waves.',
      },
    ],
  },
  history: {
    category: categories[1],
    questions: [
      {
        id: "1",
        text: 'In which year did World War II end?',
        options: ['1943', '1945', '1947', '1950'],
        correctAnswer: 1,
        explanation: 'World War II ended in 1945 with the surrender of Germany in May and Japan in September.',
      },
      {
        id: "2",
        text: 'Who was the first President of the United States?',
        options: ['Thomas Jefferson', 'John Adams', 'George Washington', 'Benjamin Franklin'],
        correctAnswer: 2,
        explanation: 'George Washington served as the first U.S. President from 1789 to 1797.',
      },
      {
        id: "3",
        text: 'Which ancient civilization built the pyramids of Giza?',
        options: ['Roman', 'Greek', 'Egyptian', 'Mesopotamian'],
        correctAnswer: 2,
        explanation: 'The ancient Egyptians built the pyramids of Giza around 2560 BCE as tombs for pharaohs.',
      },
      {
        id: "4",
        text: 'What event marked the beginning of World War I?',
        options: [
          'Invasion of Poland',
          'Assassination of Archduke Franz Ferdinand',
          'Bombing of Pearl Harbor',
          'Signing of the Treaty of Versailles',
        ],
        correctAnswer: 1,
        explanation: 'The assassination of Archduke Franz Ferdinand of Austria-Hungary in 1914 triggered the start of World War I.',
      },
      {
        id: "5",
        text: 'Which empire was ruled by Julius Caesar?',
        options: ['Roman Empire', 'Greek Empire', 'Persian Empire', 'Byzantine Empire'],
        correctAnswer: 0,
        explanation: 'Julius Caesar was a Roman general and statesman who played a critical role in the rise of the Roman Empire.',
      },
    ],
  },
  medicine: {
    category: categories[2],
    questions: [
      {
        id: "1",
        text: 'What is the normal human body temperature in Celsius?',
        options: ['35.0°C', '37.0°C', '39.0°C', '41.0°C'],
        correctAnswer: 1,
        explanation: 'Normal human body temperature is approximately 37°C (98.6°F), though it can vary slightly.',
      },
      {
        id: "2",
        text: 'Which organ pumps blood throughout the body?',
        options: ['Liver', 'Heart', 'Lungs', 'Kidneys'],
        correctAnswer: 1,
        explanation: 'The heart is a muscular organ that pumps blood through the circulatory system.',
      },
      {
        id: "3",
        text: 'What vitamin is produced when skin is exposed to sunlight?',
        options: ['Vitamin A', 'Vitamin C', 'Vitamin D', 'Vitamin K'],
        correctAnswer: 2,
        explanation: 'Vitamin D is synthesized in the skin when exposed to UVB rays from sunlight.',
      },
      {
        id: "4",
        text: 'How many bones are in the adult human body?',
        options: ['206', '210', '215', '220'],
        correctAnswer: 0,
        explanation: 'The adult human skeleton typically has 206 bones. Babies are born with about 270 bones that fuse together.',
      },
      {
        id: "5",
        text: 'Which blood type is known as the universal donor?',
        options: ['A+', 'B+', 'AB+', 'O-'],
        correctAnswer: 3,
        explanation: 'O- negative blood can be transfused to any blood type, making it the universal donor type.',
      },
    ],
  },
  'artificial-intelligence': {
    category: categories[3],
    questions: [
      {
        id: "1",
        text: 'What does "AI" stand for?',
        options: [
          'Automated Intelligence',
          'Artificial Intelligence',
          'Advanced Intelligence',
          'Algorithmic Intelligence',
        ],
        correctAnswer: 1,
        explanation: 'AI (Artificial Intelligence) refers to computer systems that can perform tasks typically requiring human intelligence.',
      },
      {
        id: "2",
        text: 'Which of these is a type of machine learning?',
        options: ['Supervised learning', 'Directed learning', 'Guided learning', 'Controlled learning'],
        correctAnswer: 0,
        explanation: 'Supervised learning is a type of ML where models learn from labeled training data.',
      },
      {
        id: "3",
        text: 'What is a neural network inspired by?',
        options: ['Computer circuits', 'The human brain', 'Mathematical formulas', 'Electrical grids'],
        correctAnswer: 1,
        explanation: 'Neural networks are computing systems inspired by the biological neural networks in animal brains.',
      },
      {
        id: "4",
        text: 'What is "natural language processing" (NLP)?',
        options: [
          'Teaching computers to understand human language',
          'Processing natural resources',
          'Analyzing programming languages',
          'Translating computer code',
        ],
        correctAnswer: 0,
        explanation: 'NLP is a field of AI that enables computers to understand, interpret, and generate human language.',
      },
      {
        id: "5",
        text: 'Which company created ChatGPT?',
        options: ['Google', 'Microsoft', 'OpenAI', 'Meta'],
        correctAnswer: 2,
        explanation: 'OpenAI developed ChatGPT, a large language model trained to generate human-like text.',
      },
    ],
  },
  'machine-learning': {
    category: categories[4],
    questions: [
      {
        id: "1",
        text: 'What is "training data" in machine learning?',
        options: [
          'Data used to test the model',
          'Data used to teach the model',
          'Data used to deploy the model',
          'Data used to visualize results',
        ],
        correctAnswer: 1,
        explanation: 'Training data is the dataset used to teach a machine learning model to recognize patterns.',
      },
      {
        id: "2",
        text: 'What is "overfitting" in machine learning?',
        options: [
          'When a model performs well on training data but poorly on new data',
          'When a model is too simple to capture patterns',
          'When a model trains too quickly',
          'When a model uses too little data',
        ],
        correctAnswer: 0,
        explanation: 'Overfitting occurs when a model memorizes training data including noise, failing to generalize to new data.',
      },
      {
        id: "3",
        text: 'What is the purpose of a "test set" in machine learning?',
        options: [
          'To train the model',
          'To evaluate model performance on unseen data',
          'To clean the data',
          'To select features',
        ],
        correctAnswer: 1,
        explanation: 'The test set evaluates how well a trained model generalizes to new, unseen data.',
      },
      {
        id: "4",
        text: 'Which algorithm is commonly used for classification tasks?',
        options: ['Linear Regression', 'K-Means', 'Logistic Regression', 'PCA'],
        correctAnswer: 2,
        explanation: 'Logistic Regression is a popular algorithm for binary and multi-class classification problems.',
      },
      {
        id: "5",
        text: 'What is a "feature" in machine learning?',
        options: [
          'The target variable to predict',
          'An input variable used for prediction',
          'The model accuracy metric',
          'The training algorithm',
        ],
        correctAnswer: 1,
        explanation: 'Features (or attributes) are the input variables that a model uses to make predictions.',
      },
    ],
  },
  'programming-languages': {
    category: categories[5],
    questions: [
      {
        id: "1",
        text: 'Which programming language is known for its use in web browsers?',
        options: ['Python', 'JavaScript', 'C++', 'Java'],
        correctAnswer: 1,
        explanation: 'JavaScript is the primary programming language for client-side web development in browsers.',
      },
      {
        id: "2",
        text: 'What does "HTML" stand for?',
        options: [
          'HyperText Markup Language',
          'High Text Markup Language',
          'Hyperlink Text Machine Language',
          'Home Tool Markup Language',
        ],
        correctAnswer: 0,
        explanation: 'HTML (HyperText Markup Language) is the standard language for creating web pages.',
      },
      {
        id: "3",
        text: 'Which language is primarily used for iOS app development?',
        options: ['Kotlin', 'Swift', 'Dart', 'Objective-C'],
        correctAnswer: 1,
        explanation: 'Swift is Apple\'s programming language for iOS, macOS, watchOS, and tvOS app development.',
      },
      {
        id: "4",
        text: 'What is a "variable" in programming?',
        options: [
          'A fixed value that never changes',
          'A named storage location for data',
          'A type of loop',
          'A function that returns nothing',
        ],
        correctAnswer: 1,
        explanation: 'A variable is a named storage location in memory that holds a value which can be changed during program execution.',
      },
      {
        id: "5",
        text: 'Which of these is a version control system?',
        options: ['Git', 'Docker', 'Kubernetes', 'Jenkins'],
        correctAnswer: 0,
        explanation: 'Git is a distributed version control system for tracking changes in source code during software development.',
      },
    ],
  },
  art: {
    category: categories[6],
    questions: [
      {
        id: "1",
        text: 'Who painted the "Mona Lisa"?',
        options: ['Vincent van Gogh', 'Pablo Picasso', 'Leonardo da Vinci', 'Michelangelo'],
        correctAnswer: 2,
        explanation: 'Leonardo da Vinci painted the Mona Lisa between 1503 and 1519. It is housed in the Louvre Museum in Paris.',
      },
      {
        id: "2",
        text: 'Which art movement is characterized by bold colors and emotional expression?',
        options: ['Impressionism', 'Expressionism', 'Realism', 'Cubism'],
        correctAnswer: 1,
        explanation: 'Expressionism emphasizes subjective emotion over realistic representation, using distorted forms and vivid colors.',
      },
      {
        id: "3",
        text: 'What technique involves painting on wet plaster?',
        options: ['Oil painting', 'Watercolor', 'Fresco', 'Acrylic'],
        correctAnswer: 2,
        explanation: 'Fresco is a mural painting technique where pigments are applied on freshly laid wet plaster.',
      },
      {
        id: "4",
        text: 'Who painted "The Starry Night"?',
        options: ['Claude Monet', 'Vincent van Gogh', 'Salvador Dalí', 'Edvard Munch'],
        correctAnswer: 1,
        explanation: 'Vincent van Gogh painted The Starry Night in 1889 during his stay at an asylum in Saint-Rémy-de-Provence.',
      },
      {
        id: "5",
        text: 'What is "perspective" in art?',
        options: [
          'The use of bright colors',
          'A technique to create depth on a flat surface',
          'The subject matter of a painting',
          'The artist\'s signature style',
        ],
        correctAnswer: 1,
        explanation: 'Perspective is a technique for representing three-dimensional objects on a two-dimensional surface to create the illusion of depth.',
      },
    ],
  },
};