import type { Category, CategoryQuizData } from './types';

export const categories: Category[] = [
  {
    id: 'technology',
    name: 'Technology',
    description: 'Computers, devices, software and the technologies shaping the modern world.',
    icon: '💻',
  },
  {
    id: 'history',
    name: 'History',
    description: 'Important people, events, civilizations and turning points.',
    icon: '🏛️',
  },
  {
    id: 'medicine',
    name: 'Medicine',
    description: 'Basic medical knowledge, human biology and healthcare concepts.',
    icon: '🩺',
  },
  {
    id: 'artificial-intelligence',
    name: 'Artificial Intelligence',
    description: 'AI concepts, applications and how intelligent systems work.',
    icon: '🤖',
  },
  {
    id: 'machine-learning',
    name: 'Machine Learning',
    description: 'Core ML concepts, models, training and practical applications.',
    icon: '🧠',
  },
  {
    id: 'programming-languages',
    name: 'Programming Languages',
    description: 'Programming concepts and practical knowledge across popular languages.',
    icon: '💾',
  },
  {
    id: 'art',
    name: 'Art',
    description: 'Art movements, artists, techniques and visual culture.',
    icon: '🎨',
  },
];

export const categoryQuizData: Record<string, CategoryQuizData> = {
  technology: {
    category: categories[0],
    questions: [
      {
        id: "1",
        text: 'What does "HTTP" stand for?',
        options: [
          'HyperText Transfer Protocol',
          'High Transfer Text Protocol',
          'Hyperlink Text Transfer Process',
          'Home Tool Transfer Protocol',
        ],
        correctAnswer: 0,
        explanation: 'HTTP (HyperText Transfer Protocol) is the foundation of data communication on the World Wide Web.',
      },
      {
        id: "2",
        text: 'Which company developed the Windows operating system?',
        options: ['Apple', 'Microsoft', 'Google', 'IBM'],
        correctAnswer: 1,
        explanation: 'Microsoft developed Windows, first released in 1985 as a graphical operating system shell for MS-DOS.',
      },
      {
        id: "3",
        text: 'What is the main function of a router in a network?',
        options: [
          'To connect devices to the internet directly',
          'To forward data packets between computer networks',
          'To store files for network users',
          'To encrypt all network traffic',
        ],
        correctAnswer: 1,
        explanation: 'A router connects multiple networks and forwards data packets between them, directing traffic efficiently.',
      },
      {
        id: "4",
        text: 'What does "URL" stand for?',
        options: [
          'Universal Resource Locator',
          'Uniform Resource Locator',
          'Universal Reference Link',
          'Uniform Reference Locator',
        ],
        correctAnswer: 1,
        explanation: 'URL (Uniform Resource Locator) is the address used to access resources on the internet.',
      },
      {
        id: "5",
        text: 'Which technology is used for wireless communication over short distances?',
        options: ['Bluetooth', 'Ethernet', 'Fiber optic', 'Coaxial cable'],
        correctAnswer: 0,
        explanation: 'Bluetooth is a wireless technology standard for exchanging data over short distances using radio waves.',
      },
    ],
  },
  history: {
    category: categories[1],
    questions: [
      {
        id: "1",
        text: 'In which year did World War II end?',
        options: ['1943', '1945', '1947', '1950'],
        correctAnswer: 1,
        explanation: 'World War II ended in 1945 with the surrender of Germany in May and Japan in September.',
      },
      {
        id: "2",
        text: 'Who was the first President of the United States?',
        options: ['Thomas Jefferson', 'John Adams', 'George Washington', 'Benjamin Franklin'],
        correctAnswer: 2,
        explanation: 'George Washington served as the first U.S. President from 1789 to 1797.',
      },
      {
        id: "3",
        text: 'Which ancient civilization built the pyramids of Giza?',
        options: ['Roman', 'Greek', 'Egyptian', 'Mesopotamian'],
        correctAnswer: 2,
        explanation: 'The ancient Egyptians built the pyramids of Giza around 2560 BCE as tombs for pharaohs.',
      },
      {
        id: "4",
        text: 'What event marked the beginning of World War I?',
        options: [
          'Invasion of Poland',
          'Assassination of Archduke Franz Ferdinand',
          'Bombing of Pearl Harbor',
          'Signing of the Treaty of Versailles',
        ],
        correctAnswer: 1,
        explanation: 'The assassination of Archduke Franz Ferdinand of Austria-Hungary in 1914 triggered the start of World War I.',
      },
      {
        id: "5",
        text: 'Which empire was ruled by Julius Caesar?',
        options: ['Roman Empire', 'Greek Empire', 'Persian Empire', 'Byzantine Empire'],
        correctAnswer: 0,
        explanation: 'Julius Caesar was a Roman general and statesman who played a critical role in the rise of the Roman Empire.',
      },
    ],
  },
  medicine: {
    category: categories[2],
    questions: [
      {
        id: "1",
        text: 'What is the normal human body temperature in Celsius?',
        options: ['35.0°C', '37.0°C', '39.0°C', '41.0°C'],
        correctAnswer: 1,
        explanation: 'Normal human body temperature is approximately 37°C (98.6°F), though it can vary slightly.',
      },
      {
        id: "2",
        text: 'Which organ pumps blood throughout the body?',
        options: ['Liver', 'Heart', 'Lungs', 'Kidneys'],
        correctAnswer: 1,
        explanation: 'The heart is a muscular organ that pumps blood through the circulatory system.',
      },
      {
        id: "3",
        text: 'What vitamin is produced when skin is exposed to sunlight?',
        options: ['Vitamin A', 'Vitamin C', 'Vitamin D', 'Vitamin K'],
        correctAnswer: 2,
        explanation: 'Vitamin D is synthesized in the skin when exposed to UVB rays from sunlight.',
      },
      {
        id: "4",
        text: 'How many bones are in the adult human body?',
        options: ['206', '210', '215', '220'],
        correctAnswer: 0,
        explanation: 'The adult human skeleton typically has 206 bones. Babies are born with about 270 bones that fuse together.',
      },
      {
        id: "5",
        text: 'Which blood type is known as the universal donor?',
        options: ['A+', 'B+', 'AB+', 'O-'],
        correctAnswer: 3,
        explanation: 'O- negative blood can be transfused to any blood type, making it the universal donor type.',
      },
    ],
  },
  'artificial-intelligence': {
    category: categories[3],
    questions: [
      {
        id: "1",
        text: 'What does "AI" stand for?',
        options: [
          'Automated Intelligence',
          'Artificial Intelligence',
          'Advanced Intelligence',
          'Algorithmic Intelligence',
        ],
        correctAnswer: 1,
        explanation: 'AI (Artificial Intelligence) refers to computer systems that can perform tasks typically requiring human intelligence.',
      },
      {
        id: "2",
        text: 'Which of these is a type of machine learning?',
        options: ['Supervised learning', 'Directed learning', 'Guided learning', 'Controlled learning'],
        correctAnswer: 0,
        explanation: 'Supervised learning is a type of ML where models learn from labeled training data.',
      },
      {
        id: "3",
        text: 'What is a neural network inspired by?',
        options: ['Computer circuits', 'The human brain', 'Mathematical formulas', 'Electrical grids'],
        correctAnswer: 1,
        explanation: 'Neural networks are computing systems inspired by the biological neural networks in animal brains.',
      },
      {
        id: "4",
        text: 'What is "natural language processing" (NLP)?',
        options: [
          'Teaching computers to understand human language',
          'Processing natural resources',
          'Analyzing programming languages',
          'Translating computer code',
        ],
        correctAnswer: 0,
        explanation: 'NLP is a field of AI that enables computers to understand, interpret, and generate human language.',
      },
      {
        id: "5",
        text: 'Which company created ChatGPT?',
        options: ['Google', 'Microsoft', 'OpenAI', 'Meta'],
        correctAnswer: 2,
        explanation: 'OpenAI developed ChatGPT, a large language model trained to generate human-like text.',
      },
    ],
  },
  'machine-learning': {
    category: categories[4],
    questions: [
      {
        id: "1",
        text: 'What is "training data" in machine learning?',
        options: [
          'Data used to test the model',
          'Data used to teach the model',
          'Data used to deploy the model',
          'Data used to visualize results',
        ],
        correctAnswer: 1,
        explanation: 'Training data is the dataset used to teach a machine learning model to recognize patterns.',
      },
      {
        id: "2",
        text: 'What is "overfitting" in machine learning?',
        options: [
          'When a model performs well on training data but poorly on new data',
          'When a model is too simple to capture patterns',
          'When a model trains too quickly',
          'When a model uses too little data',
        ],
        correctAnswer: 0,
        explanation: 'Overfitting occurs when a model memorizes training data including noise, failing to generalize to new data.',
      },
      {
        id: "3",
        text: 'What is the purpose of a "test set" in machine learning?',
        options: [
          'To train the model',
          'To evaluate model performance on unseen data',
          'To clean the data',
          'To select features',
        ],
        correctAnswer: 1,
        explanation: 'The test set evaluates how well a trained model generalizes to new, unseen data.',
      },
      {
        id: "4",
        text: 'Which algorithm is commonly used for classification tasks?',
        options: ['Linear Regression', 'K-Means', 'Logistic Regression', 'PCA'],
        correctAnswer: 2,
        explanation: 'Logistic Regression is a popular algorithm for binary and multi-class classification problems.',
      },
      {
        id: "5",
        text: 'What is a "feature" in machine learning?',
        options: [
          'The target variable to predict',
          'An input variable used for prediction',
          'The model accuracy metric',
          'The training algorithm',
        ],
        correctAnswer: 1,
        explanation: 'Features (or attributes) are the input variables that a model uses to make predictions.',
      },
    ],
  },
  'programming-languages': {
    category: categories[5],
    questions: [
      {
        id: 'prog-001',
        text: 'Which programming language is known for its use in web browsers?',
        options: ['Python', 'JavaScript', 'C++', 'Java'],
        correctAnswer: 1,
        explanation: 'JavaScript is the primary programming language for client-side web development in browsers.',
      },
      {
        id: 'prog-002',
        text: 'What does "HTML" stand for?',
        options: [
          'HyperText Markup Language',
          'High Text Markup Language',
          'Hyperlink Text Machine Language',
          'Home Tool Markup Language',
        ],
        correctAnswer: 0,
        explanation: 'HTML (HyperText Markup Language) is the standard language for creating web pages.',
      },
      {
        id: 'prog-003',
        text: 'Which language is primarily used for iOS app development?',
        options: ['Kotlin', 'Swift', 'Dart', 'Objective-C'],
        correctAnswer: 1,
        explanation: "Swift is Apple's programming language for iOS, macOS, watchOS, and tvOS app development.",
      },
      {
        id: 'prog-004',
        text: 'What is a "variable" in programming?',
        options: [
          'A fixed value that never changes',
          'A named storage location for data',
          'A type of loop',
          'A function that returns nothing',
        ],
        correctAnswer: 1,
        explanation: 'A variable is a named storage location in memory that holds a value which can be changed during program execution.',
      },
      {
        id: 'prog-005',
        text: 'Which of these is a version control system?',
        options: ['Git', 'Docker', 'Kubernetes', 'Jenkins'],
        correctAnswer: 0,
        explanation: 'Git is a distributed version control system for tracking changes in source code during software development.',
      },
      {
        id: 'prog-006',
        text: 'What does the === operator check in JavaScript?',
        options: ['Equality only', 'Strict equality (value and type)', 'Inequality', 'Assignment'],
        correctAnswer: 1,
        explanation: 'The === operator in JavaScript checks both value and type for strict equality.',
      },
      {
        id: 'prog-007',
        text: 'Which method adds an element to the end of an array in JavaScript?',
        options: ['push()', 'pop()', 'shift()', 'unshift()'],
        correctAnswer: 0,
        explanation: 'The push() method adds one or more elements to the end of an array in JavaScript.',
      },
      {
        id: 'prog-008',
        text: 'Which keyword is used to define a function in Python?',
        options: ['func', 'def', 'function', 'define'],
        correctAnswer: 1,
        explanation: 'Python uses the def keyword to define a function.',
      },
      {
        id: 'prog-009',
        text: 'Which data type is immutable in Python?',
        options: ['list', 'dict', 'tuple', 'set'],
        correctAnswer: 2,
        explanation: 'Tuples are immutable in Python, meaning their contents cannot be changed after creation.',
      },
      {
        id: 'prog-010',
        text: 'How do you start a block of code in Python?',
        options: ['Curly braces', 'Indentation', 'Semicolons', 'Parentheses'],
        correctAnswer: 1,
        explanation: 'Python uses indentation to define blocks of code, unlike other languages that use curly braces.',
      },
      {
        id: 'prog-011',
        text: 'Which function converts a string to an integer in Python?',
        options: ['str()', 'int()', 'float()', 'convert()'],
        correctAnswer: 1,
        explanation: 'The int() function converts a string to an integer in Python.',
      },
      {
        id: 'prog-012',
        text: 'Which keyword is used to define a class in Java?',
        options: ['class', 'struct', 'define', 'type'],
        correctAnswer: 0,
        explanation: 'Java uses the class keyword to define a class.',
      },
      {
        id: 'prog-013',
        text: 'What is the main entry point for a Java application?',
        options: ['main()', 'start()', 'run()', 'execute()'],
        correctAnswer: 0,
        explanation: 'The main() method is the entry point for Java applications.',
      },
      {
        id: 'prog-014',
        text: 'Which keyword is used to inherit a class in Java?',
        options: ['implements', 'extends', 'inherits', 'super'],
        correctAnswer: 1,
        explanation: 'Java uses the extends keyword for class inheritance.',
      },
      {
        id: 'prog-015',
        text: 'What is the default value of an int variable in Java?',
        options: ['0', 'null', 'undefined', '-1'],
        correctAnswer: 0,
        explanation: 'The default value of an int in Java is 0.',
      },
      {
        id: 'prog-016',
        text: 'Which symbol is used to declare a pointer variable in C?',
        options: ['&', '*', '#', '->'],
        correctAnswer: 1,
        explanation: 'The asterisk (*) is used to declare a pointer in C.',
      },
      {
        id: 'prog-017',
        text: 'What is the standard input function in C?',
        options: ['printf', 'scanf', 'cin', 'read'],
        correctAnswer: 1,
        explanation: 'scanf is the standard function for reading input in C.',
      },
      {
        id: 'prog-018',
        text: 'Which header file contains standard I/O functions in C?',
        options: ['stdlib.h', 'string.h', 'stdio.h', 'math.h'],
        correctAnswer: 2,
        explanation: 'stdio.h is the header file for standard input/output functions in C.',
      },
      {
        id: 'prog-019',
        text: 'Which operator is used to access members of an object in C++?',
        options: ['->', '.', '::', ':'],
        correctAnswer: 1,
        explanation: 'The dot (.) operator is used to access members of an object directly.',
      },
      {
        id: 'prog-020',
        text: 'What is a template in C++?',
        options: ['A design pattern', 'A way to write generic code', 'A memory allocation technique', 'A debugging tool'],
        correctAnswer: 1,
        explanation: 'C++ templates allow writing generic code that works with any data type.',
      },
      {
        id: 'prog-021',
        text: 'Which keyword begins an exception handling block in C++?',
        options: ['try', 'catch', 'throw', 'finally'],
        correctAnswer: 0,
        explanation: 'The try keyword begins a block that monitors for exceptions in C++.',
      },
      {
        id: 'prog-022',
        text: 'Which keyword is used to create an instance of a class in C#?',
        options: ['new', 'create', 'instantiate', 'make'],
        correctAnswer: 0,
        explanation: 'The new keyword is used to create an instance of a class in C#.',
      },
      {
        id: 'prog-023',
        text: 'What is the entry point method in a C# program?',
        options: ['Main()', 'Start()', 'Run()', 'Initialize()'],
        correctAnswer: 0,
        explanation: 'The Main() method is the entry point of a C# application.',
      },
      {
        id: 'prog-024',
        text: 'Which framework is C# primarily associated with?',
        options: ['Django', 'Spring', '.NET', 'Node.js'],
        correctAnswer: 2,
        explanation: 'C# is primarily developed by Microsoft as part of the .NET framework.',
      },
      {
        id: 'prog-025',
        text: 'Which keyword is used to define a function in Go?',
        options: ['func', 'function', 'def', 'method'],
        correctAnswer: 0,
        explanation: 'Go uses the func keyword to define a function.',
      },
      {
        id: 'prog-026',
        text: 'What is the zero value for a string in Go?',
        options: ['""', 'null', 'None', 'undefined'],
        correctAnswer: 0,
        explanation: 'The zero value for a string in Go is an empty string ("").',
      },
      {
        id: 'prog-027',
        text: 'Which type of concurrency does Go use?',
        options: ['Threads', 'Coroutines', 'Goroutines', 'Fibers'],
        correctAnswer: 2,
        explanation: 'Go uses goroutines for lightweight concurrent execution.',
      },
      {
        id: 'prog-028',
        text: 'Which keyword makes a variable mutable in Rust?',
        options: ['mut', 'var', 'let', 'change'],
        correctAnswer: 0,
        explanation: 'The mut keyword is used with let to declare a mutable variable in Rust.',
      },
      {
        id: 'prog-029',
        text: 'What is the package manager for Rust?',
        options: ['npm', 'pip', 'cargo', 'maven'],
        correctAnswer: 2,
        explanation: 'Cargo is the package manager and build system for Rust.',
      },
      {
        id: 'prog-030',
        text: 'Which operator is used to dereference a pointer in Rust?',
        options: ['*', '&', '->', '.'],
        correctAnswer: 0,
        explanation: 'The asterisk (*) operator is used to dereference a pointer in Rust.',
      },
      {
        id: 'prog-031',
        text: 'Which symbol is used to prefix variables in PHP?',
        options: ['$', '#', '@', '%'],
        correctAnswer: 0,
        explanation: 'PHP variables are prefixed with the dollar sign ($).',
      },
      {
        id: 'prog-032',
        text: 'What is the primary use of PHP?',
        options: ['Mobile app development', 'Server-side web development', 'Desktop applications', 'Game development'],
        correctAnswer: 1,
        explanation: 'PHP is primarily used for server-side web development.',
      },
      {
        id: 'prog-033',
        text: 'Which function checks if a variable is empty in PHP?',
        options: ['empty()', 'isnull()', 'check()', 'isempty()'],
        correctAnswer: 0,
        explanation: 'The empty() function checks whether a variable is considered empty in PHP.',
      },
      {
        id: 'prog-034',
        text: 'Which keyword is used to declare a constant in Swift?',
        options: ['let', 'const', 'final', 'static'],
        correctAnswer: 0,
        explanation: 'Swift uses the let keyword to declare a constant.',
      },
      {
        id: 'prog-035',
        text: 'Which keyword is used to define a structure in Swift?',
        options: ['struct', 'class', 'interface', 'type'],
        correctAnswer: 0,
        explanation: 'Swift uses the struct keyword to define a structure.',
      },
      {
        id: 'prog-036',
        text: 'Which keyword defines a function in Kotlin?',
        options: ['func', 'fun', 'function', 'def'],
        correctAnswer: 1,
        explanation: 'Kotlin uses the fun keyword to define a function.',
      },
      {
        id: 'prog-037',
        text: 'Which keyword declares a read-only variable in Kotlin?',
        options: ['val', 'var', 'let', 'const'],
        correctAnswer: 0,
        explanation: 'Kotlin uses val to declare a read-only (immutable) variable.',
      },
      {
        id: 'prog-038',
        text: 'What is the default base class for all classes in Kotlin?',
        options: ['Any', 'Object', 'Base', 'Root'],
        correctAnswer: 0,
        explanation: 'In Kotlin, the default base class for all classes is Any.',
      },
      {
        id: 'prog-039',
        text: 'What does IDE stand for?',
        options: ['Integrated Development Environment', 'Internal Development Engine', 'Interactive Development Editor', 'Integrated Design Environment'],
        correctAnswer: 0,
        explanation: 'IDE stands for Integrated Development Environment, a software application for writing and testing code.',
      },
      {
        id: 'prog-040',
        text: 'What is the purpose of a compiler?',
        options: ['To execute code line by line', 'To translate source code to machine code', 'To debug programs', 'To format source code'],
        correctAnswer: 1,
        explanation: 'A compiler translates source code into machine code before execution.',
      },
    ],
  },
  art: {
    category: categories[6],
    questions: [
      {
        id: "1",
        text: 'Who painted the "Mona Lisa"?',
        options: ['Vincent van Gogh', 'Pablo Picasso', 'Leonardo da Vinci', 'Michelangelo'],
        correctAnswer: 2,
        explanation: 'Leonardo da Vinci painted the Mona Lisa between 1503 and 1519. It is housed in the Louvre Museum in Paris.',
      },
      {
        id: "2",
        text: 'Which art movement is characterized by bold colors and emotional expression?',
        options: ['Impressionism', 'Expressionism', 'Realism', 'Cubism'],
        correctAnswer: 1,
        explanation: 'Expressionism emphasizes subjective emotion over realistic representation, using distorted forms and vivid colors.',
      },
      {
        id: "3",
        text: 'What technique involves painting on wet plaster?',
        options: ['Oil painting', 'Watercolor', 'Fresco', 'Acrylic'],
        correctAnswer: 2,
        explanation: 'Fresco is a mural painting technique where pigments are applied on freshly laid wet plaster.',
      },
      {
        id: "4",
        text: 'Who painted "The Starry Night"?',
        options: ['Claude Monet', 'Vincent van Gogh', 'Salvador Dalí', 'Edvard Munch'],
        correctAnswer: 1,
        explanation: 'Vincent van Gogh painted The Starry Night in 1889 during his stay at an asylum in Saint-Rémy-de-Provence.',
      },
      {
        id: "5",
        text: 'What is "perspective" in art?',
        options: [
          'The use of bright colors',
          'A technique to create depth on a flat surface',
          'The subject matter of a painting',
          'The artist\'s signature style',
        ],
        correctAnswer: 1,
        explanation: 'Perspective is a technique for representing three-dimensional objects on a two-dimensional surface to create the illusion of depth.',
      },
    ],
  },
};